### ISSUE TITLE
function theme_colors cannot return color in variable.scss

### ISSUE THREAD

**Issue by lam-nguyen247** [RHPTeam/css-library-rhp#3]

**Comment by trantoan960** [comment]
when import scss architecture,
```
@import "fuctions"
@import "variables"
@import "mixins"
```

**Comment by chinhho1996** [comment]
@import "functions";
@import "variables";
@import "mixins/mixins";

**Comment by lnguyen24794** [comment]
> when import scss architecture,
> 
> ```
> @import "fuctions"
> @import "variables"
> @import "mixins"
> ```



> @import "functions";
> @import "variables";
> @import "mixins/mixins";
